version: 2.0
gencode: databases/gencode.gff3
pirbase: databases/piRNA.gtf
mirbase: databases/hsa.gff3
trnagencode: databases/tRNA.gff3

#v1.1
# gencode: /WORKING/databases/gencode/gencode.v26.annotation.gff3
# pirbase: /WORKING/databases/pirbase/piR_hg38_hglft_genome_7460_c9ff20.filtered.gtf
# mirbase: ~/data/miRBase/hsa.gff3
# mirgenedb: /WORKING/databases/mirgenedb/mirgenedb.gff
# trnagencode: /WORKING/databases/gencode/gencode.v25.tRNAs.gff3
